name: Weekly Reddit Fetch

on:
  schedule:
    - cron: '30 5 * * 2'  # Runs every Tuesday at 11:00 AM IST (UTC +5.5 = 5:30 AM UTC)
  workflow_dispatch:  # Allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run Reddit Fetcher
        run: python fetch_reddit.py

      - name: Rewrite with DeepSeek AI
        run: python rewrite_with_ai.py
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Generate LinkedIn Image
        run: python generate_image.py
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}

